// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fdm_fcs_h)
#define octave_mx_fdm_fcs_h 1
#include "fCDiagMatrix.h"
#include "fDiagMatrix.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
DMS_BIN_OP_DECLS (FloatComplexDiagMatrix, FloatDiagMatrix, FloatComplex, OCTAVE_API)
#endif
