// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_fcs_frv_h)
#define octave_vx_fcs_frv_h 1
#include "fCRowVector.h"
#include "oct-cmplx.h"
#include "fRowVector.h"
#include "mx-op-decl.h"
SV_BIN_OP_DECLS (FloatComplexRowVector, FloatComplex, FloatRowVector, OCTAVE_API)
#endif
