// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fm_fdm_h)
#define octave_mx_fm_fdm_h 1
#include "fMatrix.h"
#include "fDiagMatrix.h"
#include "mx-op-decl.h"
MDM_BIN_OP_DECLS (FloatMatrix, FloatMatrix, FloatDiagMatrix, OCTAVE_API)
#endif
