// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fm_fcm_h)
#define octave_mx_fm_fcm_h 1
#include "fCMatrix.h"
#include "fMatrix.h"
#include "mx-op-decl.h"
MM_BIN_OP_DECLS (FloatComplexMatrix, FloatMatrix, FloatComplexMatrix, OCTAVE_API)
MM_CMP_OP_DECLS (FloatMatrix, FloatComplexMatrix, OCTAVE_API)
MM_BOOL_OP_DECLS (FloatMatrix, FloatComplexMatrix, OCTAVE_API)
#endif
