// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fnda_i8_h)
#define octave_mx_fnda_i8_h 1
#include "int8NDArray.h"
#include "fNDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (int8NDArray, FloatNDArray, octave_int8, OCTAVE_API)
NDS_CMP_OP_DECLS (FloatNDArray, octave_int8, OCTAVE_API)
NDS_BOOL_OP_DECLS (FloatNDArray, octave_int8, OCTAVE_API)
#endif
