// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_fccv_fcv_h)
#define octave_vx_fccv_fcv_h 1
#include "fCColVector.h"
#include "fColVector.h"
#include "mx-op-decl.h"
VV_BIN_OP_DECLS (FloatComplexColumnVector, FloatComplexColumnVector, FloatColumnVector, OCTAVE_API)
#endif
