// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui64_nda_h)
#define octave_mx_ui64_nda_h 1
#include "uint64NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (uint64NDArray, octave_uint64, NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (octave_uint64, NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint64, NDArray, OCTAVE_API)
#endif
