// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i32nda_s_h)
#define octave_mx_i32nda_s_h 1
#include "int32NDArray.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (int32NDArray, int32NDArray, double, OCTAVE_API)
NDS_CMP_OP_DECLS (int32NDArray, double, OCTAVE_API)
NDS_BOOL_OP_DECLS (int32NDArray, double, OCTAVE_API)
#endif
