// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_cs_h)
#define octave_mx_nda_cs_h 1
#include "CNDArray.h"
#include "dNDArray.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (ComplexNDArray, NDArray, Complex, OCTAVE_API)
NDS_CMP_OP_DECLS (NDArray, Complex, OCTAVE_API)
NDS_BOOL_OP_DECLS (NDArray, Complex, OCTAVE_API)
#endif
