// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_pm_cm_h)
#define octave_mx_pm_cm_h 1
#include "CMatrix.h"
#include "PermMatrix.h"
#include "mx-op-decl.h"
PMM_BIN_OP_DECLS (ComplexMatrix, PermMatrix, ComplexMatrix, OCTAVE_API)
#endif
