// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i64_fnda_h)
#define octave_mx_i64_fnda_h 1
#include "int64NDArray.h"
#include "oct-inttypes.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (int64NDArray, octave_int64, FloatNDArray, OCTAVE_API)
SND_CMP_OP_DECLS (octave_int64, FloatNDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_int64, FloatNDArray, OCTAVE_API)
#endif
