// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cm_m_h)
#define octave_mx_cm_m_h 1
#include "CMatrix.h"
#include "dMatrix.h"
#include "mx-op-decl.h"
MM_BIN_OP_DECLS (ComplexMatrix, ComplexMatrix, Matrix, OCTAVE_API)
MM_CMP_OP_DECLS (ComplexMatrix, Matrix, OCTAVE_API)
MM_BOOL_OP_DECLS (ComplexMatrix, Matrix, OCTAVE_API)
#endif
