// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i16nda_i32_h)
#define octave_mx_i16nda_i32_h 1
#include "int16NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (int16NDArray, octave_int32, OCTAVE_API)
NDS_BOOL_OP_DECLS (int16NDArray, octave_int32, OCTAVE_API)
#endif
