// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_i16_h)
#define octave_mx_nda_i16_h 1
#include "int16NDArray.h"
#include "dNDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (int16NDArray, NDArray, octave_int16, OCTAVE_API)
NDS_CMP_OP_DECLS (NDArray, octave_int16, OCTAVE_API)
NDS_BOOL_OP_DECLS (NDArray, octave_int16, OCTAVE_API)
#endif
