// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui16nda_ui64_h)
#define octave_mx_ui16nda_ui64_h 1
#include "uint16NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (uint16NDArray, octave_uint64, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint16NDArray, octave_uint64, OCTAVE_API)
#endif
