// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_sm_m_h)
#define octave_smx_sm_m_h 1
#include "dMatrix.h"
#include "dSparse.h"
#include "Sparse-op-defs.h"
SPARSE_SMM_BIN_OP_DECLS (Matrix, SparseMatrix, SparseMatrix, Matrix, OCTAVE_API)
SPARSE_SMM_CMP_OP_DECLS (SparseMatrix, Matrix, OCTAVE_API)
SPARSE_SMM_BOOL_OP_DECLS (SparseMatrix, Matrix, OCTAVE_API)
#endif
