// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcdm_fm_h)
#define octave_mx_fcdm_fm_h 1
#include "fCMatrix.h"
#include "fCDiagMatrix.h"
#include "fMatrix.h"
#include "mx-op-decl.h"
DMM_BIN_OP_DECLS (FloatComplexMatrix, FloatComplexDiagMatrix, FloatMatrix, OCTAVE_API)
#endif
