// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui8nda_fnda_h)
#define octave_mx_ui8nda_fnda_h 1
#include "uint8NDArray.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (uint8NDArray, uint8NDArray, FloatNDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (uint8NDArray, FloatNDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (uint8NDArray, FloatNDArray, OCTAVE_API)
#endif
