// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_fcv_fcs_h)
#define octave_vx_fcv_fcs_h 1
#include "fCColVector.h"
#include "fColVector.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
VS_BIN_OP_DECLS (FloatComplexColumnVector, FloatColumnVector, FloatComplex, OCTAVE_API)
#endif
