// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui16nda_fnda_h)
#define octave_mx_ui16nda_fnda_h 1
#include "uint16NDArray.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (uint16NDArray, uint16NDArray, FloatNDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (uint16NDArray, FloatNDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (uint16NDArray, FloatNDArray, OCTAVE_API)
#endif
