// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui64nda_i32_h)
#define octave_mx_ui64nda_i32_h 1
#include "uint64NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (uint64NDArray, octave_int32, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint64NDArray, octave_int32, OCTAVE_API)
#endif
