// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fdm_fcdm_h)
#define octave_mx_fdm_fcdm_h 1
#include "fCDiagMatrix.h"
#include "fDiagMatrix.h"
#include "mx-op-decl.h"
DMDM_BIN_OP_DECLS (FloatComplexDiagMatrix, FloatDiagMatrix, FloatComplexDiagMatrix, OCTAVE_API)
#endif
