// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_s_scm_h)
#define octave_smx_s_scm_h 1
#include "CMatrix.h"
#include "CSparse.h"
#include "Sparse-op-defs.h"
SPARSE_SSM_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, double, SparseComplexMatrix, OCTAVE_API)
SPARSE_SSM_CMP_OP_DECLS (double, SparseComplexMatrix, OCTAVE_API)
SPARSE_SSM_BOOL_OP_DECLS (double, SparseComplexMatrix, OCTAVE_API)
#endif
