// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fs_fcdm_h)
#define octave_mx_fs_fcdm_h 1
#include "fCDiagMatrix.h"
#include "mx-op-decl.h"
SDM_BIN_OP_DECLS (FloatComplexDiagMatrix, float, FloatComplexDiagMatrix, OCTAVE_API)
#endif
