// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cdm_cm_h)
#define octave_mx_cdm_cm_h 1
#include "CMatrix.h"
#include "CDiagMatrix.h"
#include "mx-op-decl.h"
DMM_BIN_OP_DECLS (ComplexMatrix, ComplexDiagMatrix, ComplexMatrix, OCTAVE_API)
#endif
