// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_rv_crv_h)
#define octave_vx_rv_crv_h 1
#include "CRowVector.h"
#include "dRowVector.h"
#include "mx-op-decl.h"
VV_BIN_OP_DECLS (ComplexRowVector, RowVector, ComplexRowVector, OCTAVE_API)
#endif
