// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_scm_sm_h)
#define octave_smx_scm_sm_h 1
#include "CSparse.h"
#include "dSparse.h"
#include "Sparse-op-defs.h"
SPARSE_SMSM_BIN_OP_DECLS (SparseComplexMatrix, SparseComplexMatrix, SparseComplexMatrix, SparseMatrix, OCTAVE_API)
SPARSE_SMSM_CMP_OP_DECLS (SparseComplexMatrix, SparseMatrix, OCTAVE_API)
SPARSE_SMSM_BOOL_OP_DECLS (SparseComplexMatrix, SparseMatrix, OCTAVE_API)
#endif
