// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fs_i8nda_h)
#define octave_mx_fs_i8nda_h 1
#include "int8NDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (int8NDArray, float, int8NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (float, int8NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (float, int8NDArray, OCTAVE_API)
#endif
