// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_ui64_h)
#define octave_mx_nda_ui64_h 1
#include "uint64NDArray.h"
#include "dNDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (uint64NDArray, NDArray, octave_uint64, OCTAVE_API)
NDS_CMP_OP_DECLS (NDArray, octave_uint64, OCTAVE_API)
NDS_BOOL_OP_DECLS (NDArray, octave_uint64, OCTAVE_API)
#endif
