// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fnda_fcs_h)
#define octave_mx_fnda_fcs_h 1
#include "fCNDArray.h"
#include "fNDArray.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (FloatComplexNDArray, FloatNDArray, FloatComplex, OCTAVE_API)
NDS_CMP_OP_DECLS (FloatNDArray, FloatComplex, OCTAVE_API)
NDS_BOOL_OP_DECLS (FloatNDArray, FloatComplex, OCTAVE_API)
#endif
