// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i64nda_fs_h)
#define octave_mx_i64nda_fs_h 1
#include "int64NDArray.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (int64NDArray, int64NDArray, float, OCTAVE_API)
NDS_CMP_OP_DECLS (int64NDArray, float, OCTAVE_API)
NDS_BOOL_OP_DECLS (int64NDArray, float, OCTAVE_API)
#endif
