// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui8nda_i8_h)
#define octave_mx_ui8nda_i8_h 1
#include "uint8NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (uint8NDArray, octave_int8, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint8NDArray, octave_int8, OCTAVE_API)
#endif
