// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fs_i16nda_h)
#define octave_mx_fs_i16nda_h 1
#include "int16NDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (int16NDArray, float, int16NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (float, int16NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (float, int16NDArray, OCTAVE_API)
#endif
