// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fs_i32nda_h)
#define octave_mx_fs_i32nda_h 1
#include "int32NDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (int32NDArray, float, int32NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (float, int32NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (float, int32NDArray, OCTAVE_API)
#endif
