// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i16nda_fs_h)
#define octave_mx_i16nda_fs_h 1
#include "int16NDArray.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (int16NDArray, int16NDArray, float, OCTAVE_API)
NDS_CMP_OP_DECLS (int16NDArray, float, OCTAVE_API)
NDS_BOOL_OP_DECLS (int16NDArray, float, OCTAVE_API)
#endif
