// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cs_dm_h)
#define octave_mx_cs_dm_h 1
#include "CDiagMatrix.h"
#include "oct-cmplx.h"
#include "dDiagMatrix.h"
#include "mx-op-decl.h"
SDM_BIN_OP_DECLS (ComplexDiagMatrix, Complex, DiagMatrix, OCTAVE_API)
#endif
