// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_cs_rv_h)
#define octave_vx_cs_rv_h 1
#include "CRowVector.h"
#include "oct-cmplx.h"
#include "dRowVector.h"
#include "mx-op-decl.h"
SV_BIN_OP_DECLS (ComplexRowVector, Complex, RowVector, OCTAVE_API)
#endif
