// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_m_pm_h)
#define octave_mx_m_pm_h 1
#include "dMatrix.h"
#include "PermMatrix.h"
#include "mx-op-decl.h"
MPM_BIN_OP_DECLS (Matrix, Matrix, PermMatrix, OCTAVE_API)
#endif
