// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui32_fnda_h)
#define octave_mx_ui32_fnda_h 1
#include "uint32NDArray.h"
#include "oct-inttypes.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (uint32NDArray, octave_uint32, FloatNDArray, OCTAVE_API)
SND_CMP_OP_DECLS (octave_uint32, FloatNDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint32, FloatNDArray, OCTAVE_API)
#endif
