// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fm_pm_h)
#define octave_mx_fm_pm_h 1
#include "fMatrix.h"
#include "PermMatrix.h"
#include "mx-op-decl.h"
MPM_BIN_OP_DECLS (FloatMatrix, FloatMatrix, PermMatrix, OCTAVE_API)
#endif
