// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_m_scm_h)
#define octave_smx_m_scm_h 1
#include "CMatrix.h"
#include "CSparse.h"
#include "dMatrix.h"
#include "Sparse-op-defs.h"
SPARSE_MSM_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, Matrix, SparseComplexMatrix, OCTAVE_API)
SPARSE_MSM_CMP_OP_DECLS (Matrix, SparseComplexMatrix, OCTAVE_API)
SPARSE_MSM_BOOL_OP_DECLS (Matrix, SparseComplexMatrix, OCTAVE_API)
#endif
