// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_s_ccv_h)
#define octave_vx_s_ccv_h 1
#include "CColVector.h"
#include "mx-op-decl.h"
SV_BIN_OP_DECLS (ComplexColumnVector, double, ComplexColumnVector, OCTAVE_API)
#endif
