// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcm_fdm_h)
#define octave_mx_fcm_fdm_h 1
#include "fCMatrix.h"
#include "fDiagMatrix.h"
#include "mx-op-decl.h"
MDM_BIN_OP_DECLS (FloatComplexMatrix, FloatComplexMatrix, FloatDiagMatrix, OCTAVE_API)
#endif
