// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui32_ui64nda_h)
#define octave_mx_ui32_ui64nda_h 1
#include "oct-inttypes.h"
#include "uint64NDArray.h"
#include "mx-op-decl.h"
SND_CMP_OP_DECLS (octave_uint32, uint64NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint32, uint64NDArray, OCTAVE_API)
#endif
