// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_fccv_fs_h)
#define octave_vx_fccv_fs_h 1
#include "fCColVector.h"
#include "mx-op-decl.h"
VS_BIN_OP_DECLS (FloatComplexColumnVector, FloatComplexColumnVector, float, OCTAVE_API)
#endif
