// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fs_ui32nda_h)
#define octave_mx_fs_ui32nda_h 1
#include "uint32NDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (uint32NDArray, float, uint32NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (float, uint32NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (float, uint32NDArray, OCTAVE_API)
#endif
