// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui64nda_s_h)
#define octave_mx_ui64nda_s_h 1
#include "uint64NDArray.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (uint64NDArray, uint64NDArray, double, OCTAVE_API)
NDS_CMP_OP_DECLS (uint64NDArray, double, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint64NDArray, double, OCTAVE_API)
#endif
