// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_cs_sm_h)
#define octave_smx_cs_sm_h 1
#include "CMatrix.h"
#include "CSparse.h"
#include "oct-cmplx.h"
#include "dSparse.h"
#include "Sparse-op-defs.h"
SPARSE_SSM_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, Complex, SparseMatrix, OCTAVE_API)
SPARSE_SSM_CMP_OP_DECLS (Complex, SparseMatrix, OCTAVE_API)
SPARSE_SSM_BOOL_OP_DECLS (Complex, SparseMatrix, OCTAVE_API)
#endif
