// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui16_nda_h)
#define octave_mx_ui16_nda_h 1
#include "uint16NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (uint16NDArray, octave_uint16, NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (octave_uint16, NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint16, NDArray, OCTAVE_API)
#endif
