// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fnda_i32nda_h)
#define octave_mx_fnda_i32nda_h 1
#include "int32NDArray.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (int32NDArray, FloatNDArray, int32NDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (FloatNDArray, int32NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (FloatNDArray, int32NDArray, OCTAVE_API)
#endif
