// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui32nda_fs_h)
#define octave_mx_ui32nda_fs_h 1
#include "uint32NDArray.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (uint32NDArray, uint32NDArray, float, OCTAVE_API)
NDS_CMP_OP_DECLS (uint32NDArray, float, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint32NDArray, float, OCTAVE_API)
#endif
