// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_sm_cs_h)
#define octave_smx_sm_cs_h 1
#include "CMatrix.h"
#include "CSparse.h"
#include "dSparse.h"
#include "oct-cmplx.h"
#include "Sparse-op-defs.h"
SPARSE_SMS_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, SparseMatrix, Complex, OCTAVE_API)
SPARSE_SMS_CMP_OP_DECLS (SparseMatrix, Complex, OCTAVE_API)
SPARSE_SMS_BOOL_OP_DECLS (SparseMatrix, Complex, OCTAVE_API)
#endif
