// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i8nda_ui8nda_h)
#define octave_mx_i8nda_ui8nda_h 1
#include "int8NDArray.h"
#include "uint8NDArray.h"
#include "mx-op-decl.h"
NDND_CMP_OP_DECLS (int8NDArray, uint8NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (int8NDArray, uint8NDArray, OCTAVE_API)
#endif
