// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_rv_cs_h)
#define octave_vx_rv_cs_h 1
#include "CRowVector.h"
#include "dRowVector.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
VS_BIN_OP_DECLS (ComplexRowVector, RowVector, Complex, OCTAVE_API)
#endif
