// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui16nda_nda_h)
#define octave_mx_ui16nda_nda_h 1
#include "uint16NDArray.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (uint16NDArray, uint16NDArray, NDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (uint16NDArray, NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (uint16NDArray, NDArray, OCTAVE_API)
#endif
