// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_m_cdm_h)
#define octave_mx_m_cdm_h 1
#include "CMatrix.h"
#include "dMatrix.h"
#include "CDiagMatrix.h"
#include "mx-op-decl.h"
MDM_BIN_OP_DECLS (ComplexMatrix, Matrix, ComplexDiagMatrix, OCTAVE_API)
#endif
