// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui64_i64nda_h)
#define octave_mx_ui64_i64nda_h 1
#include "oct-inttypes.h"
#include "int64NDArray.h"
#include "mx-op-decl.h"
SND_CMP_OP_DECLS (octave_uint64, int64NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint64, int64NDArray, OCTAVE_API)
#endif
