// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcs_fnda_h)
#define octave_mx_fcs_fnda_h 1
#include "fCNDArray.h"
#include "oct-cmplx.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (FloatComplexNDArray, FloatComplex, FloatNDArray, OCTAVE_API)
SND_CMP_OP_DECLS (FloatComplex, FloatNDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (FloatComplex, FloatNDArray, OCTAVE_API)
#endif
