// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcs_fm_h)
#define octave_mx_fcs_fm_h 1
#include "fCMatrix.h"
#include "oct-cmplx.h"
#include "fMatrix.h"
#include "mx-op-decl.h"
SM_BIN_OP_DECLS (FloatComplexMatrix, FloatComplex, FloatMatrix, OCTAVE_API)
SM_CMP_OP_DECLS (FloatComplex, FloatMatrix, OCTAVE_API)
SM_BOOL_OP_DECLS (FloatComplex, FloatMatrix, OCTAVE_API)
#endif
