// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_sbm_bm_h)
#define octave_smx_sbm_bm_h 1
#include "boolMatrix.h"
#include "boolSparse.h"
#include "Sparse-op-defs.h"
SPARSE_SMM_EQNE_OP_DECLS (SparseBoolMatrix, boolMatrix, OCTAVE_API)
SPARSE_SMM_BOOL_OP_DECLS (SparseBoolMatrix, boolMatrix, OCTAVE_API)
#endif
