// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i16_nda_h)
#define octave_mx_i16_nda_h 1
#include "int16NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (int16NDArray, octave_int16, NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (octave_int16, NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_int16, NDArray, OCTAVE_API)
#endif
