// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i16nda_i64nda_h)
#define octave_mx_i16nda_i64nda_h 1
#include "int16NDArray.h"
#include "int64NDArray.h"
#include "mx-op-decl.h"
NDND_CMP_OP_DECLS (int16NDArray, int64NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (int16NDArray, int64NDArray, OCTAVE_API)
#endif
