// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cdm_s_h)
#define octave_mx_cdm_s_h 1
#include "CDiagMatrix.h"
#include "mx-op-decl.h"
DMS_BIN_OP_DECLS (ComplexDiagMatrix, ComplexDiagMatrix, double, OCTAVE_API)
#endif
