// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcnda_fnda_h)
#define octave_mx_fcnda_fnda_h 1
#include "fCNDArray.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (FloatComplexNDArray, FloatComplexNDArray, FloatNDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (FloatComplexNDArray, FloatNDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (FloatComplexNDArray, FloatNDArray, OCTAVE_API)
#endif
