// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i32_ui32nda_h)
#define octave_mx_i32_ui32nda_h 1
#include "oct-inttypes.h"
#include "uint32NDArray.h"
#include "mx-op-decl.h"
SND_CMP_OP_DECLS (octave_int32, uint32NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_int32, uint32NDArray, OCTAVE_API)
#endif
