// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_m_cs_h)
#define octave_mx_m_cs_h 1
#include "CMatrix.h"
#include "dMatrix.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
MS_BIN_OP_DECLS (ComplexMatrix, Matrix, Complex, OCTAVE_API)
MS_CMP_OP_DECLS (Matrix, Complex, OCTAVE_API)
MS_BOOL_OP_DECLS (Matrix, Complex, OCTAVE_API)
#endif
