// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i8nda_i16_h)
#define octave_mx_i8nda_i16_h 1
#include "int8NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (int8NDArray, octave_int16, OCTAVE_API)
NDS_BOOL_OP_DECLS (int8NDArray, octave_int16, OCTAVE_API)
#endif
