// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_bm_sbm_h)
#define octave_smx_bm_sbm_h 1
#include "boolMatrix.h"
#include "boolSparse.h"
#include "Sparse-op-defs.h"
SPARSE_MSM_EQNE_OP_DECLS (boolMatrix, SparseBoolMatrix, OCTAVE_API)
SPARSE_MSM_BOOL_OP_DECLS (boolMatrix, SparseBoolMatrix, OCTAVE_API)
#endif
