// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_ui8_h)
#define octave_mx_nda_ui8_h 1
#include "uint8NDArray.h"
#include "dNDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (uint8NDArray, NDArray, octave_uint8, OCTAVE_API)
NDS_CMP_OP_DECLS (NDArray, octave_uint8, OCTAVE_API)
NDS_BOOL_OP_DECLS (NDArray, octave_uint8, OCTAVE_API)
#endif
