// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fs_ui64nda_h)
#define octave_mx_fs_ui64nda_h 1
#include "uint64NDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (uint64NDArray, float, uint64NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (float, uint64NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (float, uint64NDArray, OCTAVE_API)
#endif
