// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_ui32nda_h)
#define octave_mx_nda_ui32nda_h 1
#include "uint32NDArray.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (uint32NDArray, NDArray, uint32NDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (NDArray, uint32NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (NDArray, uint32NDArray, OCTAVE_API)
#endif
