// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcm_fm_h)
#define octave_mx_fcm_fm_h 1
#include "fCMatrix.h"
#include "fMatrix.h"
#include "mx-op-decl.h"
MM_BIN_OP_DECLS (FloatComplexMatrix, FloatComplexMatrix, FloatMatrix, OCTAVE_API)
MM_CMP_OP_DECLS (FloatComplexMatrix, FloatMatrix, OCTAVE_API)
MM_BOOL_OP_DECLS (FloatComplexMatrix, FloatMatrix, OCTAVE_API)
#endif
