// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_s_cm_h)
#define octave_mx_s_cm_h 1
#include "CMatrix.h"
#include "mx-op-decl.h"
SM_BIN_OP_DECLS (ComplexMatrix, double, ComplexMatrix, OCTAVE_API)
SM_CMP_OP_DECLS (double, ComplexMatrix, OCTAVE_API)
SM_BOOL_OP_DECLS (double, ComplexMatrix, OCTAVE_API)
#endif
