// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fm_fcs_h)
#define octave_mx_fm_fcs_h 1
#include "fCMatrix.h"
#include "fMatrix.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
MS_BIN_OP_DECLS (FloatComplexMatrix, FloatMatrix, FloatComplex, OCTAVE_API)
MS_CMP_OP_DECLS (FloatMatrix, FloatComplex, OCTAVE_API)
MS_BOOL_OP_DECLS (FloatMatrix, FloatComplex, OCTAVE_API)
#endif
