// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fnda_i32_h)
#define octave_mx_fnda_i32_h 1
#include "int32NDArray.h"
#include "fNDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (int32NDArray, FloatNDArray, octave_int32, OCTAVE_API)
NDS_CMP_OP_DECLS (FloatNDArray, octave_int32, OCTAVE_API)
NDS_BOOL_OP_DECLS (FloatNDArray, octave_int32, OCTAVE_API)
#endif
