// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i32nda_fnda_h)
#define octave_mx_i32nda_fnda_h 1
#include "int32NDArray.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (int32NDArray, int32NDArray, FloatNDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (int32NDArray, FloatNDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (int32NDArray, FloatNDArray, OCTAVE_API)
#endif
