// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui16nda_s_h)
#define octave_mx_ui16nda_s_h 1
#include "uint16NDArray.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (uint16NDArray, uint16NDArray, double, OCTAVE_API)
NDS_CMP_OP_DECLS (uint16NDArray, double, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint16NDArray, double, OCTAVE_API)
#endif
