// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_i16nda_h)
#define octave_mx_nda_i16nda_h 1
#include "int16NDArray.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (int16NDArray, NDArray, int16NDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (NDArray, int16NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (NDArray, int16NDArray, OCTAVE_API)
#endif
