// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_pm_m_h)
#define octave_mx_pm_m_h 1
#include "dMatrix.h"
#include "PermMatrix.h"
#include "mx-op-decl.h"
PMM_BIN_OP_DECLS (Matrix, PermMatrix, Matrix, OCTAVE_API)
#endif
