// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcnda_fs_h)
#define octave_mx_fcnda_fs_h 1
#include "fCNDArray.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (FloatComplexNDArray, FloatComplexNDArray, float, OCTAVE_API)
NDS_CMP_OP_DECLS (FloatComplexNDArray, float, OCTAVE_API)
NDS_BOOL_OP_DECLS (FloatComplexNDArray, float, OCTAVE_API)
#endif
