// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fs_ui8nda_h)
#define octave_mx_fs_ui8nda_h 1
#include "uint8NDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (uint8NDArray, float, uint8NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (float, uint8NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (float, uint8NDArray, OCTAVE_API)
#endif
