// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_dm_cdm_h)
#define octave_mx_dm_cdm_h 1
#include "CDiagMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-decl.h"
DMDM_BIN_OP_DECLS (ComplexDiagMatrix, DiagMatrix, ComplexDiagMatrix, OCTAVE_API)
#endif
