// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cs_m_h)
#define octave_mx_cs_m_h 1
#include "CMatrix.h"
#include "oct-cmplx.h"
#include "dMatrix.h"
#include "mx-op-decl.h"
SM_BIN_OP_DECLS (ComplexMatrix, Complex, Matrix, OCTAVE_API)
SM_CMP_OP_DECLS (Complex, Matrix, OCTAVE_API)
SM_BOOL_OP_DECLS (Complex, Matrix, OCTAVE_API)
#endif
