// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_scm_s_h)
#define octave_smx_scm_s_h 1
#include "CMatrix.h"
#include "CSparse.h"
#include "Sparse-op-defs.h"
SPARSE_SMS_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, SparseComplexMatrix, double, OCTAVE_API)
SPARSE_SMS_CMP_OP_DECLS (SparseComplexMatrix, double, OCTAVE_API)
SPARSE_SMS_BOOL_OP_DECLS (SparseComplexMatrix, double, OCTAVE_API)
#endif
