// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_dm_cm_h)
#define octave_mx_dm_cm_h 1
#include "CMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-decl.h"
DMM_BIN_OP_DECLS (ComplexMatrix, DiagMatrix, ComplexMatrix, OCTAVE_API)
#endif
