// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_frv_fcs_h)
#define octave_vx_frv_fcs_h 1
#include "fCRowVector.h"
#include "fRowVector.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
VS_BIN_OP_DECLS (FloatComplexRowVector, FloatRowVector, FloatComplex, OCTAVE_API)
#endif
