// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_ui64nda_h)
#define octave_mx_nda_ui64nda_h 1
#include "uint64NDArray.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (uint64NDArray, NDArray, uint64NDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (NDArray, uint64NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (NDArray, uint64NDArray, OCTAVE_API)
#endif
