// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_cm_sm_h)
#define octave_smx_cm_sm_h 1
#include "CMatrix.h"
#include "CSparse.h"
#include "dSparse.h"
#include "Sparse-op-defs.h"
SPARSE_MSM_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, ComplexMatrix, SparseMatrix, OCTAVE_API)
SPARSE_MSM_CMP_OP_DECLS (ComplexMatrix, SparseMatrix, OCTAVE_API)
SPARSE_MSM_BOOL_OP_DECLS (ComplexMatrix, SparseMatrix, OCTAVE_API)
#endif
