// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i64nda_ui64nda_h)
#define octave_mx_i64nda_ui64nda_h 1
#include "int64NDArray.h"
#include "uint64NDArray.h"
#include "mx-op-decl.h"
NDND_CMP_OP_DECLS (int64NDArray, uint64NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (int64NDArray, uint64NDArray, OCTAVE_API)
#endif
