// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fnda_i64_h)
#define octave_mx_fnda_i64_h 1
#include "int64NDArray.h"
#include "fNDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (int64NDArray, FloatNDArray, octave_int64, OCTAVE_API)
NDS_CMP_OP_DECLS (FloatNDArray, octave_int64, OCTAVE_API)
NDS_BOOL_OP_DECLS (FloatNDArray, octave_int64, OCTAVE_API)
#endif
