// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_pm_fm_h)
#define octave_mx_pm_fm_h 1
#include "fMatrix.h"
#include "PermMatrix.h"
#include "mx-op-decl.h"
PMM_BIN_OP_DECLS (FloatMatrix, PermMatrix, FloatMatrix, OCTAVE_API)
#endif
