// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_cv_cs_h)
#define octave_vx_cv_cs_h 1
#include "CColVector.h"
#include "dColVector.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
VS_BIN_OP_DECLS (ComplexColumnVector, ColumnVector, Complex, OCTAVE_API)
#endif
