// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cnda_s_h)
#define octave_mx_cnda_s_h 1
#include "CNDArray.h"
#include "mx-op-decl.h"
NDS_BIN_OP_DECLS (ComplexNDArray, ComplexNDArray, double, OCTAVE_API)
NDS_CMP_OP_DECLS (ComplexNDArray, double, OCTAVE_API)
NDS_BOOL_OP_DECLS (ComplexNDArray, double, OCTAVE_API)
#endif
