// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_i32nda_nda_h)
#define octave_mx_i32nda_nda_h 1
#include "int32NDArray.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (int32NDArray, int32NDArray, NDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (int32NDArray, NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (int32NDArray, NDArray, OCTAVE_API)
#endif
