// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fs_fcnda_h)
#define octave_mx_fs_fcnda_h 1
#include "fCNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (FloatComplexNDArray, float, FloatComplexNDArray, OCTAVE_API)
SND_CMP_OP_DECLS (float, FloatComplexNDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (float, FloatComplexNDArray, OCTAVE_API)
#endif
