// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcm_fcdm_h)
#define octave_mx_fcm_fcdm_h 1
#include "fCMatrix.h"
#include "fCDiagMatrix.h"
#include "mx-op-decl.h"
MDM_BIN_OP_DECLS (FloatComplexMatrix, FloatComplexMatrix, FloatComplexDiagMatrix, OCTAVE_API)
#endif
