// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cm_s_h)
#define octave_mx_cm_s_h 1
#include "CMatrix.h"
#include "mx-op-decl.h"
MS_BIN_OP_DECLS (ComplexMatrix, ComplexMatrix, double, OCTAVE_API)
MS_CMP_OP_DECLS (ComplexMatrix, double, OCTAVE_API)
MS_BOOL_OP_DECLS (ComplexMatrix, double, OCTAVE_API)
#endif
