// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_cm_pm_h)
#define octave_mx_cm_pm_h 1
#include "CMatrix.h"
#include "PermMatrix.h"
#include "mx-op-decl.h"
MPM_BIN_OP_DECLS (ComplexMatrix, ComplexMatrix, PermMatrix, OCTAVE_API)
#endif
