// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_pm_fcm_h)
#define octave_mx_pm_fcm_h 1
#include "fCMatrix.h"
#include "PermMatrix.h"
#include "mx-op-decl.h"
PMM_BIN_OP_DECLS (FloatComplexMatrix, PermMatrix, FloatComplexMatrix, OCTAVE_API)
#endif
