// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_vx_fs_fccv_h)
#define octave_vx_fs_fccv_h 1
#include "fCColVector.h"
#include "mx-op-decl.h"
SV_BIN_OP_DECLS (FloatComplexColumnVector, float, FloatComplexColumnVector, OCTAVE_API)
#endif
