// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_dm_m_h)
#define octave_mx_dm_m_h 1
#include "dMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-decl.h"
DMM_BIN_OP_DECLS (Matrix, DiagMatrix, Matrix, OCTAVE_API)
#endif
