// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fnda_i8nda_h)
#define octave_mx_fnda_i8nda_h 1
#include "int8NDArray.h"
#include "fNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (int8NDArray, FloatNDArray, int8NDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (FloatNDArray, int8NDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (FloatNDArray, int8NDArray, OCTAVE_API)
#endif
