// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_nda_cnda_h)
#define octave_mx_nda_cnda_h 1
#include "CNDArray.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
NDND_BIN_OP_DECLS (ComplexNDArray, NDArray, ComplexNDArray, OCTAVE_API)
NDND_CMP_OP_DECLS (NDArray, ComplexNDArray, OCTAVE_API)
NDND_BOOL_OP_DECLS (NDArray, ComplexNDArray, OCTAVE_API)
#endif
