// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui8_nda_h)
#define octave_mx_ui8_nda_h 1
#include "uint8NDArray.h"
#include "oct-inttypes.h"
#include "dNDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (uint8NDArray, octave_uint8, NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (octave_uint8, NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (octave_uint8, NDArray, OCTAVE_API)
#endif
