// DO NOT EDIT -- generated by sparse-mk-ops
#if !defined (octave_smx_scm_cm_h)
#define octave_smx_scm_cm_h 1
#include "CMatrix.h"
#include "CSparse.h"
#include "Sparse-op-defs.h"
SPARSE_SMM_BIN_OP_DECLS (ComplexMatrix, SparseComplexMatrix, SparseComplexMatrix, ComplexMatrix, OCTAVE_API)
SPARSE_SMM_CMP_OP_DECLS (SparseComplexMatrix, ComplexMatrix, OCTAVE_API)
SPARSE_SMM_BOOL_OP_DECLS (SparseComplexMatrix, ComplexMatrix, OCTAVE_API)
#endif
