// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_ui32nda_i64_h)
#define octave_mx_ui32nda_i64_h 1
#include "uint32NDArray.h"
#include "oct-inttypes.h"
#include "mx-op-decl.h"
NDS_CMP_OP_DECLS (uint32NDArray, octave_int64, OCTAVE_API)
NDS_BOOL_OP_DECLS (uint32NDArray, octave_int64, OCTAVE_API)
#endif
