// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_s_i64nda_h)
#define octave_mx_s_i64nda_h 1
#include "int64NDArray.h"
#include "mx-op-decl.h"
SND_BIN_OP_DECLS (int64NDArray, double, int64NDArray, OCTAVE_API)
SND_CMP_OP_DECLS (double, int64NDArray, OCTAVE_API)
SND_BOOL_OP_DECLS (double, int64NDArray, OCTAVE_API)
#endif
